<b>Задания на повторение материала**</b>

<b>1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно</b>

In [1]:
import numpy as np

In [2]:
a = np.arange(12,24,1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

<b>2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.</b>

In [3]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [7]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

<b>3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).</b>

In [8]:
b1 = a.reshape(2, -1)
b1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
b2 = a.reshape(3, -1)
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
b3 = a.reshape(4, -1)
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [11]:
b4 = a.reshape(-1, 2)
b4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [12]:
b4 = a.reshape(-1, 1)
b4

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

<b>4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?</b>

In [13]:
# Посмотрим размерность массива, который состоит из одного столбца и 12 строк:
b1.ndim

2

Значит такой массив определяется Numpy, как двухмерный.\
Ответ: массив Numpy, состоящий из одного столбца и 12 строк, нельзя назвать одномерным.

<b>5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.</b>

In [14]:
sigma = 1.0
mean = 0
r = sigma * np.random.randn(3,4) + mean
print(f'size = {r.size}')
r

size = 12


array([[ 2.1790809 , -0.0484333 ,  0.52389478, -1.75645652],
       [ 0.11845161,  0.85214887,  1.76641098, -0.92646014],
       [-1.19442198,  0.3058203 , -0.53532339, -0.44829078]])

In [15]:
rf = r.flatten()
print(f'size = {rf.size}')
rf

size = 12


array([ 2.1790809 , -0.0484333 ,  0.52389478, -1.75645652,  0.11845161,
        0.85214887,  1.76641098, -0.92646014, -1.19442198,  0.3058203 ,
       -0.53532339, -0.44829078])

<b>6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.</b>

In [16]:
a = np.arange(20, 0, -2)
print(f'a = {a}')

a = [20 18 16 14 12 10  8  6  4  2]


<b>7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?</b>

In [17]:
b = np.arange(20, 1, -2).reshape(1, 10)
print(f'b = {b}')

b = [[20 18 16 14 12 10  8  6  4  2]]


Массивы a и b отличаются размерностью:

In [18]:
print(f'a.ndim = {a.ndim}')
print(f'b.ndim = {b.ndim}')

a.ndim = 1
b.ndim = 2


<b>8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.</b>

In [19]:
a = np.zeros([2, 2], dtype = int)
print(f'a = \n{a}')

a = 
[[0 0]
 [0 0]]


In [20]:
b = np.ones([3, 2], dtype = int)
print(f'b = \n{b}')

b = 
[[1 1]
 [1 1]
 [1 1]]


In [21]:
v  = np.vstack([a, b])
print(f'v = \n{v}')
print(f'v.size = {v.size}')

v = 
[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]
v.size = 10


<b>9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
</b>

In [22]:
a = np.arange(0, 12, 1, dtype = int)
print(f'a = {a}')

a = [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [23]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
At = A.transpose()
print(f'At = \n{At}')

At = 
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [25]:
B = np.dot(A, At)
print(f'B = \n{B}')
print(f'Размерность B = {np.ndim(B)}')
print(f'Количество элементов B = {B.size}')
print(f'Размер B = {np.shape(B)}')

B = 
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Размерность B = 2
Количество элементов B = 16
Размер B = (4, 4)


Матрица B имеет размерность 4x4. Она квадратная, т.е. можно было бы попробовать для неё найти обратную матрицу. \
Но определитель матрицы B равен нулю, а в этом случае найти обратную матрицу не можем.\
При попытке найти обратную матрицу (строка закомментирована), получаем ошибку "LinAlgError: Singular matrix".

In [26]:
print(f'Определитель B = {np.linalg.det(B)}')
# print(np.linalg.inv(B))

Определитель B = 0.0


<b>10. Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.</b>

In [27]:
np.random.seed(42)

<b>11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.</b>

In [28]:
c = np.random.randint(0, 16, 16)
print(f'c = {c}')

c = [ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


<b>12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.</b>

In [29]:
C = c.reshape([4, 4])
print(f'C = \n{C}')

C = 
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [30]:
D = C * 10 + B
print(f'D = \n{D}')

D = 
[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]


In [31]:
print(f'Определитель D = {np.linalg.det(D)}')

Определитель D = -28511999.999999944


In [32]:
print(f'Ранг D = {np.linalg.matrix_rank(D)}')

Ранг D = 4


In [33]:
D_inv = np.linalg.inv(D)
print(f'D_inv = \n{D_inv}')

D_inv = 
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


<b>13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.</b>

In [34]:
D_inv_new = np.where(D_inv < 0, 0, 1) 
# Сделал другое имя для матрицы, чтобы не перезатирать исходную матрицу и не перезапускать все шаги снова
print(D_inv_new)

[[1 1 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 1 0]]


In [35]:
i = np.where((D_inv_new != 0) | (D_inv_new != 1), 0, 1)
if(i.sum()):
    print('В данной матрице есть элементы отличающиеся от 0 или 1')
else:
    print('В данной матрице нет элементов отличающихся от 0 или 1')

В данной матрице нет элементов отличающихся от 0 или 1


In [36]:
E = np.where(D_inv_new == 1, B, C)
print(f'E = \n{E}')

E = 
[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
