<b>Задание 1</b>\
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]]
            )
print(f'Массив: \n{a}')

mean_a = a.mean(axis=0)
print(f'Среднее по столбцам: { mean_a }')

Массив: 
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Среднее по столбцам: [2.  8.4]


<b>Задание 2</b>\
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [2]:
a_centered = a - a.mean(axis=0)
print(f'Массив "отцентрированных" значений признаков:\n {a_centered}')

Массив "отцентрированных" значений признаков:
 [[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


<b>Задание 3</b> \
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [3]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
print(f'a_centered_sp = {a_centered_sp}')
print(f'a_centered_sp / (N - 1) = {a_centered_sp / (len(a_centered[:,0]) - 1)}')

a_centered_sp = 8.0
a_centered_sp / (N - 1) = 2.0


<b>Задание 4**</b>\
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.\
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [4]:
m = np.transpose(a)
print(f'Транспонированная матрица a = \n{m}\n')
a_cov = np.cov(m)
print(f'Ковариационная матрица = \n{np.cov(m)}\n')
cov = a_cov[0, 1]
print(f'Значение ковариации = {cov}')

Транспонированная матрица a = 
[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]

Ковариационная матрица = 
[[1.  2. ]
 [2.  4.3]]

Значение ковариации = 2.0
